{
  "hash": "3fdd537c7a21fbbbb1609a6f3ef3cc49",
  "result": {
    "markdown": "---\ntitle: \"Connecting the three dots: An HSB Model\"\nauthor: \"Luke Miratrix\"\neditor: \n  markdown: \n    wrap: sentence\n---\n\n\n\n\n\nThis handout shows (1) the mathematical model, (2) the `lmer` syntax, and (3) the output for the model, as discussed in class in Lecture 2.4.\nThis handout is designed to help translate between these three different worlds.\n\n## The mathematical model\n\nLevel 1 models: $$\n\\begin{aligned}\ny_{ij} &= \\beta_{0j} + \\beta_{1j} ses_{ij} + \\beta_2 female_{ij} +  \\epsilon_{ij} \\\\\n\\epsilon_{ij} &\\sim N( 0, \\sigma^2_y ) \\\\\n\\end{aligned}\n$$\n\nLevel 2 models: $$\n\\begin{aligned}\n\\beta_{0j} &= \\gamma_{00} + \\gamma_{01} sector_j + \\gamma_{02} meanSES_j + u_{0j} \\\\\n\\beta_{1j} &= \\gamma_{10} + \\gamma_{11} sector_j + u_{1j} \n\\end{aligned}\n$$ with $$\n\\begin{pmatrix} u_{0j} \\\\\nu_{1j}\n\\end{pmatrix} \\sim  N\n\\begin{bmatrix}\n\\begin{pmatrix}\n0 \\\\\n0\n\\end{pmatrix}\\!\\!,&\n\\begin{pmatrix}\n\\tau_{00} & \\tau_{01}\\\\\n & \\tau_{11} \\\\\n\\end{pmatrix}\n\\end{bmatrix} .\n$$\n\nThe $\\tau_{01}$ is the covariance of the random intercept and random slope.\nWe usually look at the correlation of\n\n$$ \\rho = \\frac{ \\tau_{01} }{ \\sqrt{ \\tau_{00} \\tau_{11} } } . $$\n\nThe estimated $\\rho$ is what R gives us in the printed output, rather than $\\tau_{01}$.\n\nThe derivation of the reduced form is:\n\n$$\n\\begin{aligned}\ny_{ij} &= \\beta_{0j} + \\beta_{1j} ses_{ij} + \\epsilon_{ij}\\\\\n&= \\left( \\gamma_{00} + \\gamma_{01} sector_j + \\gamma_{02} meanSES_j + u_{0j} \\right)+ (\\gamma_{10} + \\gamma_{11} sector_j + u_{1j}) ses_{ij} + \\beta_2 female_{ij} + \\epsilon_{ij} \\\\\n&= \\gamma_{00} + \\gamma_{01} sector_j + \\gamma_{02} meanSES_j  + u_{0j}  + \\gamma_{10}ses_{ij} + \\gamma_{11} sector_j ses_{ij} + u_{1j} ses_{ij} + \\beta_2 female_{ij} +  \\epsilon_{ij}  \\\\\n&= \\gamma_{00} + \\gamma_{01} sector_j + \\gamma_{02} meanSES_j +  \\gamma_{10}ses_{ij} + \\gamma_{11} sector_j ses_{ij} + \\beta_2 female_{ij}  + \\left(u_{0j} + u_{1j} ses_{ij} + \\epsilon_{ij} \\right) \n\\end{aligned}\n$$ This formula is what we will give to `lmer()` in R's formula notation.\n\n## The lmer code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nM1 = lmer( mathach ~ 1 + female + ses*sector + \n             meanses + (1+ses|id),\n           data = dat )\n```\n:::\n\n\n\nThis code is the exact same model, using the fact that `ses*sector` means `ses + sector + ses:sector`.\nI.e., the above is exactly the same as this more explicitly written R code:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nM1 = lmer( mathach ~ 1 + sector + meanses + ses + sector:ses + female + (1+ses|id),\n           data = dat )\n```\n:::\n\n\n\nEach term in the expanded formula corresponds to a math symbol in the mathematical model.\nThe `(1+ses|id)` make our random effects, and tie to all the $\\tau$ terms.\nThe residual variance $\\sigma^2_y$ is the only parameter not explicitly listed in the above model.\n\n## The output\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndisplay( M1 )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlmer(formula = mathach ~ 1 + sector + meanses + ses + sector:ses + \n    female + (1 + ses | id), data = dat)\n            coef.est coef.se\n(Intercept) 12.79     0.21  \nsector       1.29     0.29  \nmeanses      3.04     0.37  \nses          2.73     0.14  \nfemale      -1.18     0.16  \nsector:ses  -1.31     0.21  \n\nError terms:\n Groups   Name        Std.Dev. Corr \n id       (Intercept) 1.45          \n          ses         0.18     0.65 \n Residual             6.05          \n---\nnumber of obs: 7185, groups: id, 160\nAIC = 46482.9, DIC = 46445.1\ndeviance = 46454.0 \n```\n:::\n:::\n\n\n\nNow, using this output, we have estimates for all our mathematical modeling parameters:\n\n-   $\\gamma_{00} = 12.79$ - The overall average math achievement for a student with 0 ses in a public school with 0 mean SES.\n-   $\\gamma_{01} = 1.29$ - The average difference between otherwise equivilent catholic and public schools.\n-   $\\gamma_{02} = 3.04$ - The impact on average achievement due to mean SES of schools. Higher SES schools have higher achievement.\n-   $\\gamma_{10} = 2.73$ - The average slope of ses vs. math achievement in public schools.\n-   $\\beta_2 = -1.18$ - The gender gap; girls have lower math scores on average.\n-   $\\gamma_{11} = -1.31$ - The difference in slope between public and catholic schools (catholic schools have flatter slopes).\n-   $\\tau_{00} = 1.45^2$ - Variation in overall intercept of schools (within category of public or catholic, and beyond mean SES).\n-   $\\tau_{11} = 0.18^2$ - The variation in the random slopes for ses vs. math achievement.\n-   $\\rho = 0.65$ - The random intercepts are correlated with random slopes. High achievement schools have more discrepancy between low and high ses students.\n-   $\\sigma_y = 6.05$ - The unexplained student variation within school.\n",
    "supporting": [
      "model_cheat_sheet_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}